<?php
    /**
     * aheadWorks Co.
     *
     * NOTICE OF LICENSE
     *
     * This source file is subject to the EULA
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://ecommerce.aheadworks.com/LICENSE-M1.txt
     *
     * @category   AW
     * @package    AW_Onsale
     * @copyright  Copyright (c) 2009-2010 aheadWorks Co. (http://www.aheadworks.com)
     * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
     */
?>
<?php $_product = $this->getProduct();?>
<?php if ( $this->isShow() || !$this->getProduct()->getIsSalable()): ?>
<?php $position = $this->getPosition();
if(!$this->getProduct()->getIsSalable()) {
    $position = 'MC';
    $this->setImageFile('', 'detail-soldout.png');
}
$img_label  = str_replace(DS,'/',$this->getImageUrl());
?>
    <div id ="product-container-<?php echo $this->getProduct()->getId(); ?>" class="onsale-product-container-inside"
         style="
             width: 100%;
             height: 100%;
             max-width: 400px;
             background-size: 70%;
             background-repeat: no-repeat;
             background-position: top right;
             z-index:100;
             background-image: url('<?php print $img_label; ?>');
             left: auto!important;
            <?php if (in_array($position, array('TL', 'TC', 'TR'))): ?>top: 0px; right: 0;<?php endif; ?>
            <?php if (in_array($position, array('BL', 'BC', 'BR'))): ?>bottom: 0px;<?php endif; ?>">
        <div id="product-onsale-label-<?php echo $this->getProduct()->getId(); ?>" class="<?php echo  $this->getType() ?>-onsale-product-label-text onsale-product-label"><span><?php if($this->getProduct()->getIsSalable()) print $this->getFormatedText() ?></span></div>
</div>
<script type="text/javascript">
    onsale.registerHorPosition($('product-container-<?php echo $this->getProduct()->getId(); ?>'), '<?php if (($position == 'TC') or ($position == 'BC') or ($position == 'MC')) print 'center'; if (($position == 'TL') or ($position == 'BL') or ($position == 'ML')) print 'left'; if (($position == 'TR') or ($position == 'BR') or ($position == 'MR')) print 'right'; ?>');
    <?php if (in_array($position, array('ML', 'MC', 'MR'))): ?>
    onsale.registerVertPosition($('product-container-<?php echo $this->getProduct()->getId(); ?>'), 'middle');
    <?php endif; ?>
    onsale.registerHorPosition($('product-onsale-label-<?php echo $this->getProduct()->getId(); ?>'), 'center');
    onsale.registerVertPosition($('product-onsale-label-<?php echo $this->getProduct()->getId(); ?>'), 'middle');
</script>
<?php endif; ?>
