<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento ENTERPRISE edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento ENTERPRISE edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
/**
 * @var $this Mage_Tax_Block_Checkout_Shipping
 * @see Mage_Tax_Block_Checkout_Shipping
 */
?>
<?php $request = $this->getRequest();
$action = $this->getRequest()->getActionName();
if (($action == 'view')||($action == 'add')) { 
$colspan = 1;
} else {
$colspan = 3;	
}
?>
<?php if ($this->displayBoth()):?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="3<?php echo $this->getColspan(); ?>">
        <?php echo $this->getExcludeTaxLabel() ?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->getShippingExcludeTax()) ?>
    </td>
</tr>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="3<?php echo $this->getColspan(); ?>">
        <?php echo $this->getIncludeTaxLabel() ?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->getShippingIncludeTax()) ?>
    </td>
</tr>
<?php elseif($this->displayIncludeTax()) : ?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="3<?php echo $this->getColspan(); ?>">
        <?php echo $this->getTotal()->getTitle() ?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->getShippingIncludeTax()) ?>
    </td>
</tr>
<?php else:?>
	<?php $_currentUrl = $this->helper('core/url')->getCurrentUrl();?>
	<?php $_baseUrl = $this->getBaseUrl(); ?>
<tr>
	<?php if ($_currentUrl == $_baseUrl || $_currentUrl ==  $_baseUrl.'awmobile/cart/estimatePost/'):?>
    	<td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
    <?php else:?>
    	<td style="<?php echo $this->getStyle() ?>" class="a-right" colspan=<?php echo $colspan;?>>
    <?php endif;?>
        <?php //echo $this->getTotal()->getTitle(); ?><?php echo $this->__('Delivery of') ?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" id="shipping-of">
        <?php echo $this->helper('checkout')->formatPrice($this->getShippingExcludeTax()) ?>
    </td>
</tr>
<?php endif;?>
