
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
    $youtube_video_id = $_product->getData('youtube_video_id');
?>
<div class="overview-specs">
    <?php if ($_product->getDescription()):?>
        <div class="overview<?php if (!$this->getChildHtml('additional')) echo "-full"; ?>">
            <h3><?php echo $this->__('Overview') ?></h3>
            <?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description') ?>
            <?php if($youtube_video_id) : ?>
                <div class="video">
                    <iframe width="572px" height="351px" src="http://www.youtube.com/embed/<?php echo $youtube_video_id ?>" frameborder="0" allowfullscreen></iframe>
                </div>
            <?php endif; ?>
        </div>
    <?php endif;?>
    <?php if ($this->getChildHtml('additional')): ?>
        <div class="specs">
            <h3><?php echo $this->__('Specifications')?></h3>
            <?php echo $this->getChildHtml('additional') ?>
        </div>
    <?php endif;?>
</div>