<div class="home-list-banner">
    <div class="banner-top">
        <?php echo $this->getChildHtml('home_banner_2_1')?>
        <?php echo $this->getChildHtml('home_banner_2_2')?>
    </div>
    <div class="banner-bottom">
        <div class="social-banner">
            <div class="facebook">
                <?php echo $this->getChildHtml('home_banner_facebook')?>
            </div>
            <div class="twitter">
                <?php echo $this->getChildHtml('home_banner_twitter')?>
            </div>
        </div>
        <div class="banner-sales">
            <?php echo $this->getChildHtml('home_banner_sale')?>
        </div>
    </div>
    <div class="banner-bottom home-banner-design">
        <?php echo $this->getChildHtml('home_banner_3_3')?>
    </div>
</div>
<div class="home_list_category">
    <?php echo $this->getChildHtml('home_list_category')?>
</div>
<div class="seo-block-homepage">
    <?php echo $this->getChildHtml('seo-block-homepage')?>
</div>