<?php $_items = $this->getReviewsCollection()->getItems();?>
<?php foreach ($_items as $_review):?>
    <dt>
        <a class="review-top-title" href="<?php echo $this->getReviewUrl($_review->getId()) ?>">
            <?php echo $this->escapeHtml($_review->getTitle()) ?>
        </a>
    </dt>
    <dd>
        <?php $_votes = $_review->getRatingVotes(); ?>

        <?php if (count($_votes)): ?>
        <table class="ratings-table">
            <col width="1" />
            <col />
            <tbody>
                <?php $percentage = 0; ?>
                <?php foreach ($_votes as $_vote): ?>
                    <?php $percentage += $_vote->getPercent() ?>
                <?php endforeach; ?>
                <tr>
                    <td>
                        <div class="review-title">
                            <?php echo $this->escapeHtml('Rating') ?>
                        </div>
                    </td>
                    <td>
                        <div class="rating-box">
                            <div class="rating" style="width:<?php echo ceil($percentage/3) ?>%;"></div>
                        </div>
                    </td>
                    <td>
                        <div class="review-details">
                            <?php echo nl2br($this->escapeHtml($_review->getDetail())) ?>
                        </div>
                        <div class="review-meta">
                            <?php echo $this->__('Review by %s', $this->escapeHtml($_review->getNickname())) ?>
                            <?php echo $this->__('Posted on %s', $this->formatDate($_review->getCreatedAt()), 'long') ?>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
        <?php endif; ?>
    </dd>
<?php endforeach; ?>
