<?php
if($this->isActive() == 1):
?>
<script type="text/javascript">
//dynamic remarketing
var google_tag_params = { 
ecomm_prodid: <?php echo $this->getCartProdid();?>,
ecomm_pagetype: 'purchase',
ecomm_totalvalue: '<?php echo $this->getTotal();?>'};
</script>
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = <?php echo $this->getConversionId();?>;
var google_conversion_label = "<?php echo $this->getConversionLabel();?>";
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="http<?php echo (Mage::app()->getStore()->isCurrentlySecure() ? 's': '');?>://www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="http<?php echo (Mage::app()->getStore()->isCurrentlySecure() ? 's': '');?>://googleads.g.doubleclick.net/pagead/viewthroughconversion/<?php echo $this->getConversionId();?>/?value=0&amp;label=<?php echo $this->getConversionLabel();?>&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
<?php endif;  ?>