<div id="bi-line-v" style="display: none"></div>
<div class="frp-inner">
    <form id="bi-frp-form">
        <div class="title"><?php echo $this->__('We\'ll cover you for any loss or damage to your order during delivery.');?>
        </div>
        <div class="option-frp">
            <input id="frp1" type="radio" value="1" name="frp" class="bi_frp" onchange="getCheckedFreightProtection()" <?php if($this->getDefaultChecked() == 1) echo 'checked'?> />
            <label for="frp1">Freight protection for just </label><span class="frp-cost"><?php echo $this->getFreightProtection();?></span>
        </div>
        <div class="option-frp">
            <input id="frp2" type="radio" value="2" name="frp" class="bi_frp" onchange="getCheckedFreightProtection()" <?php if($this->getDefaultChecked() == 2)  echo 'checked'?> />
            <label for="frp2">No, Thank you!</label>
        </div>
        <span class="please-wait" id="frp-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading Freight Protection...') ?>" title="<?php echo $this->__('Loading Freight Protection...') ?>" class="v-middle" /> <?php echo $this->__('Loading Freight Protection...') ?>
        </span>
        <?php $protection = $this->getRequest()->getParam('protection'); ?>
        <?php if ($protection == 1 && !($this->getDefaultChecked() ==1 || $this->getDefaultChecked() ==2)): ?>
            <div class="validation-advice" id="advice-required-shipping-method"><?php echo $this->__('Please choose an option above.'); ?></div>
            <script type="text/javascript">
                scrollToElm = '#bi-frp-form';
                if (jQuery("#postcode.validation-failed").length > 0) {
                    scrollToElm = '#postcode.validation-failed';
                }
                jQuery('html, body').animate({
                    scrollTop: jQuery(scrollToElm).offset().top
                }, 200);
            </script>
        <?php endif; ?>
    </form>
</div>

<script type="text/javascript">
    //<![CDATA[

   /*$('bi-frp-form').on('change', '.bi_frp', function(event) {
        if ($('frp1').checked == true) {
            setFreightProtection(1);
        } else if ($('frp2').checked == true) {
            setFreightProtection(0);
        }
    });*/
    <?php /*
    $("bi_tooltip").observe('mouseover', function() {
        var indicator = "<ul id=\"tooltip_freight\" style=\" color: #79797a; font-size:10px;line-height: 1.5;margin-left: 392px;margin-right: 40px;margin-top: -64px;padding: 5px;position: absolute;z-index: 2222;border:3px solid #71b5ff;text-align: center;width: 198px;background-color: #FFFFFF;\">" +
            "<li>Premium Freight Protection. We will cover any loss or damage to your order that occurs during delivery.</li>" +
            "</ul>";
        if(!$('tooltip_freight'))
        {
            $('bi_tooltip_insert').insert(indicator);
        }
    });


    $("bi_tooltip").observe('mouseout', function() {
        if ($('tooltip_freight')) $('tooltip_freight').remove();
    });
    */
    ?>

    function getCheckedFreightProtection()
    {
        removeClassNotSelect();
        if ($('frp1').checked == true) {
            setFreightProtection(1);
        } else if ($('frp2').checked == true) {
            setFreightProtection(2);
        }
    }
    function removeClassNotSelect()
    {
        if ($('bi-freight-protection-radio').hasClassName('bi-frp-not-select')) $('bi-freight-protection-radio').removeClassName('bi-frp-not-select');
        if ($('bi-line-v')) $('bi-line-v').hide();
    }

    function setFreightProtection(freight_protection){
        $('frp-please-wait').show();
        new Ajax.Request("<?php echo Mage::getUrl('shippingprotection/index/updatefreightprotection',array('_secure'=>Mage::app()->getFrontController()->getRequest()->isSecure()))?>", {
            method: 'post',
            parameters:{freight_protection:freight_protection},
            onSuccess: function(data) {
                $('frp-please-wait').hide();
                if (jQuery('.result-price-shipping').length > 0) {
                    if (jQuery('.result-price-shipping .price').html() != '') {
                        jQuery('.button-disabled').removeClass('button-disabled');
                    }
                }

            },
            onComplete: function(data) {
                $('frp-please-wait').hide();
                var dataResponse	=	data.responseJSON;
                if (jQuery('.result-price-shipping').length > 0) {
                    if (jQuery('.result-price-shipping .price').html() != '') {
                        jQuery('.button-disabled').removeClass('button-disabled');
                    }
                }

               if($('shopping-cart-totals-freight-protection')) $('shopping-cart-totals-freight-protection').update(dataResponse.totals);


                    if (Prototype.Browser.IE) {
                        $$('span.regular-price span[class="price"]').each(function(item){
                            var html = $(item).innerHTML;
                            if(html.search('<sup>') == -1 && html.search('</sup>') == -1 && html.search('<SUP>') == -1) {
                                var html_currency = html.sub('$', '<sup>$</sup>');
                                var html_price = html_currency.sub('.', '<sup>.') + '</sup>';
                                item.update(html_price);
                            }
                        });
                        $$('p.special-price span[class="price"]').each(function(item){
                            var html = $(item).innerHTML;
                            if(html.search('<sup>') == -1 && html.search('</sup>') == -1 && html.search('<SUP>') == -1) {
                                var html_currency = html.sub('$', '<sup>$</sup>');
                                var html_price = html_currency.sub('.', '<sup>.') + '</sup>';
                                item.update(html_price);
                            }
                        });
                    } else {
                        $$('span.regular-price span[class="price"]').each(function(item){
                            var html = $(item).innerHTML;
                            if(html.search('<sup>') == -1 && html.search('</sup>') == -1) {
                                var html_currency = html.sub('$', '<sup>$</sup>');
                                var html_price = html_currency.sub('.', '<sup>.') + '</sup>';
                                item.update(html_price);
                            }
                        });

                        $$('p.special-price span[class="price"]').each(function(item){
                            var html = $(item).innerHTML;
                            if(html.search('<sup>') == -1 && html.search('</sup>') == -1) {
                                var html_currency = html.sub('$', '<sup>$</sup>');
                                var html_price = html_currency.sub('.', '<sup>.') + '</sup>';
                                item.update(html_price);
                            }
                        });
                    }

            }
        });

    }


    //]]>
</script>