<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Ez\\Util\\' => array($vendorDir . '/ez/util/src'),
    'Ez\\MageCli\\' => array($vendorDir . '/ez/mage-cli/src'),
    'Ez\\MageBridge\\' => array($vendorDir . '/ez/mage-bridge/src'),
    'Ez\\DataStructure\\' => array($vendorDir . '/ez/data-structure/src'),
);
