  <ul class="links">
            <?php echo $this->getChildHtml('footer_links_about_us') ?>
<?php if (Mage::helper('customer')->isLoggedIn()): ?>
    <li><a title="My Account" href="<?php echo $this->getUrl('customer/account/') ?>">My Account</a>
    <li class="last"><a title="Log Out" href="<?php echo $this->getUrl('customer/account/logout') ?>">Log Out</a>
    <?php else: ?>
    <li class="last"><a title="Trade login" href="<?php echo $this->getUrl('customer/account/login') ?>" id="login-link">Trade login</a>
    <?php endif; ?>
</li>
</ul>