<?php
    $post=$this->getPost();
    if($post->getId()):
?>
<div class="postContent"><?php echo $post->getData('post_content'); ?></div>
<?php echo $this->getBookmarkHtml($post) ?>
<div class="tags"><?php echo $this->getTagsHtml($post) ?></div>
<div class="clear"></div>
<div class="share-buttons" id="blog_<?php echo $post->getId();?>"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('share-buttons')->toHtml() ?></div>

<?php
$title = $post->getTitle();
$summary = $post->getData('meta_description');
$currentUrl = $post->getAddress();
$image =$this->getSkinUrl('images/logo.gif');
?>
<div id="facebook_share_link_<?php echo $post->getId();?>" class="no-display">
    <a id="facebook-share-link" onClick="window.open('http://www.facebook.com/sharer.php?s=100&p[title]=<?php echo urlencode($title);?>&p[summary]=<?php echo urlencode($summary);?>&p[url]=<?php echo urlencode($currentUrl); ?>&p[images][0]=<?php echo urlencode($image);?>', 'sharer', 'toolbar=0,status=0,width=550,height=400');" target="_parent" href="javascript: void(0)">
        <img src="<?php echo $this->getSkinUrl('images/facebook_share.gif') ?>"/>
    </a>
</div>
<div class="postDetails">
    <?php if($this->getCommentsEnabled()): ?>
        <div class="tags">
            <h2>Have a Comment?</h2>
        </div>
        <?php
        $commentCount =	$post->getCommentCount();
        if($commentCount > 0):
            $comments = $this->getComment($post);
            ?>
            <?php foreach ($comments as $comment) : ?>
            <div class="commentWrapper">
                <div class="commentDetails">
                    <h4 class="username"><?php echo $comment->getUser();?></h4>
              <span class="comment-date"><?php $commentPostedDate =  $comment->getCreatedTime();?>
                  <?php echo date("D",strtotime($commentPostedDate)) .' '.date("jS",strtotime($commentPostedDate)) .' '.date("F",strtotime($createdTime)) .',  '.date("Y",strtotime($createdTime));?> </span></div>
                <div class="commentContent"><?php echo nl2br($comment->getComment());?></div>
            </div>
        <?php endforeach; ?>
        <?php endif; ?>
        <!--form-section start here-->
        <div class="Blog-form-section">
        <div class="blog-form-top-corn"></div>
        <?php
        $submitUrl = Mage::getUrl('blog/post/view', array(
            'id'        => $post->getPostId()
        ));

        if ($post->getComments()): ?>
            <div class="postError"><?php echo Mage::helper('blog')->__('Comments are Closed for this post') ?></div>
        <?php else:
        if ($this->getLoginRequired()):
        if ($this->helper('customer')->isLoggedIn()): ?>
            <form action="<?php echo $submitUrl; ?>" id="postComment" method="post" class="aw-post-comment">
                <?php echo $this->getBlockHtml('formkey') ?>
                <fieldset class="group-select">
                    <h4 class="legend"><?php echo Mage::helper('blog')->__('Your reply') ?></h4>
                    <ul class="form-list">
                        <li>
                            <div class="input-box aw-blog-comment-area">
                                <label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label>
                                <textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry input-text"><?php echo $this->getCommentText(); ?></textarea>
                            </div>
                        </li>
                    </ul>
                </fieldset>
                <div class="button-set" style="width:95%;">
                    <input name="post_id" type="hidden" value="<?php echo $post->getPostId();?>" />
                    <!--   <input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserEmail()) ?>"/> -->
                    <input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserName()) ?>"/>
                    <p class="required" style="width:100%"><?php echo $this->__('* Required Fields') ?></p>
                    <button class="button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                </div>
            </form>
            </div>
            <script type="text/javascript">
                var contactForm = new VarienForm('postComment', false);
            </script>
        <?php else: ?>
            <p><?php echo Mage::helper('blog')->__('You must be logged in to post a comment.');?></p>
            <p><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('blog')->__('click here');?></a> <?php echo Mage::helper('blog')->__('to log in');?></p>
        <?php endif ?>
        <?php else: ?>
            <form action="<?php echo $submitUrl; ?>" id="postComment" method="post" class="aw-post-comment">
                <?php echo $this->getBlockHtml('formkey') ?>
                <fieldset class="group-select">
                    <h2 class="legend"><?php echo Mage::helper('blog')->__('Your reply') ?></h2>
                    <ul class="form-list">
                        <li>
                            <div class="input-box">
                                <label class="required" for="name"><?php echo Mage::helper('blog')->__('Name') ?> <em>*</em></label>
                                <input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" title="<?php echo $this->__('Name') ?>" style="height:16px;" class="required-entry input-text" type="text" />
                            </div>
                            <!--
                            <div class="input-box">
                                <label class="required" for="email"><?php echo Mage::helper('blog')->__('Email') ?> <em>*</em></label><br />
                                <input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" class="required-entry input-text validate-email" type="text" />
                            </div>
							-->

                            <div class="input-box1 aw-blog-comment-area">
                                <label class="required" for="comment"><?php echo Mage::helper('blog')->__('Comment') ?> <em>*</em></label>
                                <div class="button-set right">
                                    <input name="post_id" type="hidden" value="<?php echo $post->getPostId();?>" />
                                    <button class="btn-submit" type="submit" title="<?php echo Mage::helper('blog')->__('Submit') ?>"></button>
                                </div>
                                <textarea name="comment" id="comment" title="<?php echo Mage::helper('blog')->__('Comment') ?>" class="required-entry input-text" style="height:16px;">
                                    <?php echo $this->getCommentText(); ?></textarea>
                                <p>Please Note : All comments must be approved to ensure their suitability for publishing.</p>
                            </div>
                        </li>
                        <?php
                        if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn())
                        {
                            ?>
                            <li>
                                <?php
                                require_once 'recaptcha/recaptchalib-aw.php';

                                // Get a key from http://recaptcha.net/api/getkey
                                $publickey = Mage::getStoreConfig('blog/recaptcha/publickey');
                                $privatekey = Mage::getStoreConfig('blog/recaptcha/privatekey');
                                $error = null;

                                echo recaptcha_get_html($publickey, $error);
                                ?>
                            </li>
                        <?php
                        }
                        ?>
                    </ul>
                </fieldset>
                <!-- <p class="required" style="text-align:left"><?php echo $this->__('* Required Fields') ?></p>-->
            </form>


            <script type="text/javascript">
                var contactForm = new VarienForm('postComment', false);
            </script>


        <?php endif; ?>
        <?php endif; ?>


        <?php //echo $post->getCommentCount(); ?>
        <!-- <a href="<?php //echo $post->getAddress(); ?>#commentBox" >Comments</a> | -->
    <?php endif; ?>  <div class="clearer"></div>

    <?php /* $postCats = $post->getCats(); ?>
		<?php if(!empty($postCats)):?>
			<?php echo Mage::helper('blog')->__('Posted in');?>
			<?php foreach($postCats as $title=>$url): ?>
				<a href="<?php echo $url; ?>"><?php echo $title; ?></a>
			<?php endforeach;?>
        <?php else:?>
        	 <?php echo Mage::helper('blog')->__('Posted');?>
        <?php endif;?><?php echo$this->__("By");?> <?php echo $post->getUser(); */ ?>
    <div class="blog-form-bottom-corn"></div>

</div>
<?php
    endif;
?>
<!--form-section end here-->