<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=<?php echo Mage::getStoreConfig('locator_settings/google_maps/api_key'); ?>&sensor=false&libraries=places"></script>

<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

<script>
    document.observe("dom:loaded", function() {
        Locator.defaultSearchSettings.baseUrl = '<?php echo Mage::getBaseUrl(); ?>';

        Locator.Map.addMethods({
            getMarkerImage: function(l){
                return new google.maps.MarkerImage(
                    '/skin/frontend/ultimo/balance/locator/images/pin.png',
                    new google.maps.Size(24, 37),
                    new google.maps.Point(0, 0),
                    new google.maps.Point(12, 37)
                );
            },
            getTheme: function(){
                return [
                    {"featureType":"water", "stylers":[{"visibility":"on"}, {"color":"#b5cbe7"}]},
                    {"featureType":"landscape", "stylers":[{"color":"#eeeeee"}]},
                    {"featureType":"road", "elementType":"geometry.fill", "stylers":[{"color":"#ffffff"}]},
                    {"featureType":"road", "elementType":"geometry.stroke", "stylers":[{"color":"#cccccc"}]},
                    {"featureType":"poi.park", "elementType":"geometry", "stylers":[{"color":"#a7d2b1"}]},
                    {"featureType":"administrative", "stylers":[{"visibility":"on"}, {"lightness":33}]},
                    { featureType: "poi.business", elementType: "labels", stylers: [ { visibility: "off" } ] }
                ];
            }
        });
    });
</script>