<?php
// Use default configurable product.
$product = Mage::getBlockSingleton('balance_superptype/catalog_product_view_type_super')->getDefaultConfigurableProduct();
if (!($product instanceof Mage_Catalog_Model_Product) || !$product->getId())
{
    return;
}
$_care_guide = $product->getCareGuide();
?>
<?php if ($_care_guide): ?>
<?php echo $this->helper('catalog/output')->productAttribute($product, $_care_guide, 'care_guide') ?>
<?php endif; ?>