<?php
/**
 * template
 */
?>
<?php if (Mage::getStoreConfig('megamenu/general/enable')): ?>
<?php
    //Mage::helper('megamenu')->getCssgen();
   $store = Mage::app()->getStore()->getId();
   //$block = $this->getLayout()->createBlock('cms/block')->setBlockId('megamenu_'.$store);
   $menu = $this->getChildHtml('menu_cached_'.$store);
   if ($menu == '') {
      Mage::helper('megamenu')->saveCacheHtml($store);
      $block = $this->getLayout()->createBlock('cms/block')->setBlockId('megamenu_'.$store);
      echo $block->toHtml();
   } else {
      echo $menu;
   }

?>
<?php else: ?>
	<?php echo $this->getChildHtml('catalog.topnav.old') ?>
<?php endif ?>