<?php
//get postcode:
$pcode = $this->getAddress()->getPostcode();
if(!$pcode) {
    //guess
    $pcode = Mage::helper('checkout')->getQuote()->getShippingAddress()->getPostcode();
}
//get address info from postcode:
$addressInfo = Mage::helper('addressbypostcode')->getAddressByPostCode($pcode);

$regionId = $this->getAddress()->getRegionId();
if(!$regionId) {
    $countryCode = Mage::getStoreConfig('general/country/default');
    $regionModel = Mage::getModel('directory/region')->loadByCode($addressInfo['state'], $countryCode);
    $regionId = $regionModel->getId();
}
$helper = Mage::helper('onestepcheckout/checkout');
$dataHelper = Mage::helper('onestepcheckout');
?>
<?php $billingFields['region_id'] = '
    <div class="input-box input-region">
        <label for="billing:region">'.$this->__('State').' <span class="required">*</span></label><br/>
        <select id="billing:region_id" name="billing[region_id]" title="'.$this->__('State/Province').'" class="validate-select" style="display:none">
            <option value="">'.$this->__('Please select').'</option>
        </select>
        <script type="text/javascript">
            $("billing:region_id").setAttribute("defaultValue",  "'.$dataHelper->clearDash($regionId).'");
        </script>
        <input type="text" id="billing:region" name="billing[region]" value="'.$dataHelper->clearDash($regionId).'"  title="'.$this->__('State/Province').'" class="required-entry input-text" style="display:none" />
    </div>';
?>
<?php echo $billingFields['region_id']; ?>
