<?php if ($this->getProduct()->isSaleable()):?>
    <div class="<?php echo $this->getStyle() ?> amstockstatus_align" style="height: auto;">
        <?php if (Mage::getStoreConfig('catalog/general/icononly')): ?>
            <?php echo Mage::helper('amstockstatus')->getStatusIconImage($this->getProduct()); ?>
        <?php else: ?>
			<?php echo Mage::helper('amstockstatus')->getStatusIconImage($this->getProduct()); ?>
            <?php echo $this->getCustomStockStatus(); ?>
            <?php if( $this->getProduct()->getPreorderCalender()):?>
                <span class="stock-status">&nbsp;<?php echo date("d/m/Y", strtotime($this->getProduct()->getPreorderCalender()));?></span>
            <?php endif;?>
        <?php endif; ?>
    </div>
<?php else: ?>
    <?php if ($this->getProduct()->getData('hide_default_stock_status')): ?>
        <div class="<?php echo $this->getStyle() ?> amstockstatus_align" style="height: auto;">
            <?php if (Mage::getStoreConfig('catalog/general/icononly')): ?>
                <?php echo Mage::helper('amstockstatus')->getStatusIconImage($this->getProduct()); ?>
            <?php else: ?>
				<?php echo Mage::helper('amstockstatus')->getStatusIconImage($this->getProduct()); ?>
                <?php echo $this->getCustomStockStatus(); ?>
                <?php if( $this->getProduct()->getPreorderCalender()):?>
                    <span class="stock-status">&nbsp;<?php echo date("d/m/Y", strtotime($this->getProduct()->getPreorderCalender()));?></span>
                <?php endif;?>
            <?php endif; ?>
        </div>
    <?php else: ?>
        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?> <?php if ($this->getCustomStockStatus()): ?> - <?php echo $this->getCustomStockStatus(); ?><?php endif; ?></span></p>
    <?php endif; ?>
<?php endif; ?>

<?php if ($this->getProduct()->getTypeId() == 'configurable'){?>
    <div class="<?php echo $this->getStyle() ?> amstockstatus_align" style="height: auto;">
     <span class="stock-status" id="stock-status-configurable"></span>
    </div>
<?php } ?>
