<?php
//get postcode:
$pcode = $this->getAddress()->getPostcode();
if(!$pcode) {
    //guess
    $pcode = Mage::helper('checkout')->getQuote()->getShippingAddress()->getPostcode();
}
//get address info from postcode:
$addressInfo = Mage::helper('addressbypostcode')->getAddressByPostCode($pcode);

$regionId = $this->getAddress()->getRegionId();
if(!$regionId) {
    $countryCode = Mage::getStoreConfig('general/country/default');
    $regionModel = Mage::getModel('directory/region')->loadByCode($addressInfo['state'], $countryCode);
    $regionId = $regionModel->getId();
}
$helper = Mage::helper('onestepcheckout/checkout');
$dataHelper = Mage::helper('onestepcheckout');
?>
<?php if ($addressInfo && is_array($addressInfo["suburb"])):?>
    <?php
    $shippingFields['city'] = '<div class="input-box input-city">
        <label for="shipping:city">'.$this->__('Suburb / Town').' <span class="required">*</span></label><br/>';
    $shippingFields['city'] .= '<select id="shipping:city" name="shipping[city]" title="'.$this->__('Suburb/Town').'" class="validate-select">';
    foreach($addressInfo["suburb"] as $suburb){
        $shippingFields['city'] .= '<option value="'.$suburb.'">'.$suburb.'</option>';
    }
    $shippingFields['city'] .= '</select>';
    $shippingFields['city'] .=  '</div>';
    ?>
<?php else: ?>
    <?php $shippingFields['city'] = '
    <div class="input-box input-city'.((in_array('city', $formErrors)) ? ' input-error' : '').'">
        <label for="shipping:city">'.$this->__('Suburb / Town').' <span class="required">*</span></label><br/>
        <input type="text" name="shipping[city]" value="'.$dataHelper->clearDash($this->getQuote()->getShippingAddress()->getCity()).'" title="'.$this->__('Suburb / Town').'" class="required-entry input-text" id="billing:city" />
    </div>';
    ?>
<?php endif; ?>
<?php echo $shippingFields['city']; ?>