<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo Mage::helper('adminhtml')->__('SAP Product Import') ?></h3></td>
            <td class="form-buttons"></td>
         </tr>
    </table>
</div>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getImportUrl()?>')" type="button" class="scalable"><span><?php echo Mage::helper('adminhtml')->__('Import Now') ?></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('Import product data from the SAP web service. This might take a minute or two.') ?>
        </td>
    </tr>
</table>
